services:
  server-dev:
    build:
      context: .
      dockerfile: server/Dockerfile.server
      target: dev
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    


  client-dev:
    build:
      context: .
      dockerfile: client/Dockerfile.client
      target: dev
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server-dev


  server-prod:
    build:
      context: .
      dockerfile: server/Dockerfile.server
      target: prod
    ports:
      - "8080:5000"
    env_file:
      - ./server/.env


  client-prod:
    build:
      context: .
      dockerfile: client/Dockerfile.client
      target: prod
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - server-prod


